### ISSUE TITLE
Bullets remain floating in air after hitting an entity.

### ISSUE THREAD

**Issue by Twilight13** [LemADEC/GunCus#10]
GunCustomization-1.7.10-3.45.0.22:

After hitting a monster and doing damage, the bullets continue to hang in the air for a few seconds before disappearing. This is especially annoying with the flamethrower from the Wholy addon, since the floating "bullets" continue to spray yellow particle effects everywhere until they disappear.

**Comment by LemADEC** [comment]
It's intended for bullets to remain in air as a visual indication of the hit location. Ideally, they should remain sticked into the entity but it was too complicated to implement.
5 seconds is indeed too long, I'll reduce it to 1 second in the next update.

**Comment by LemADEC** [comment]
Fixed in a9280fa739dfc7f4d5fead6eaf43573aa1f93c52
