### ISSUE TITLE
Default knockback should probably be 0. Use "Impact" to add desired amount.

### ISSUE THREAD

**Issue by Twilight13** [LemADEC/GunCus#12]
GunCustomization-1.7.10-3.45.0.22:

The impact setting for different bullet types has an option to add knockback to the weapon:
"10:X:Y = knockback +X horizontally +Y vertically."
but there is already fairly heavy knock back built in by default. It might be good to set the default knockback to 0, and let users customize any knockback with the impact setting, in case you have a weapon you want little, or no knockback on. Currently, there is no way to have less than the (considerable) default knockback.

**Comment by LemADEC** [comment]
The default knockback comes from vanilla code itself when 2 entities are hitting each others. We probably need a coremod to fix that one.

**Comment by LemADEC** [comment]
Found an easy fix for that, will be in next update

**Comment by LemADEC** [comment]
Fixed in 6a0fb5114323ade96010a5a4199a54d4db642982
