### ISSUE TITLE
MCHeli Damage issues

### ISSUE THREAD

**Issue by ghost** [LemADEC/GunCus#15]
When shooting helicopters from MCHeli, occasionally, bullets I presume unintentionally "ricochet" back at the player.  The bullets also never damage the helicopter, which is treated as an entity that you ride.

**Comment by LemADEC** [comment]
While shooting forward, does the bullet hit you when moving forward? when moving backward?

**Comment by ghost** [comment]
Any action can replicate the same issue. I found it to occur the most
whilst not moving though.

**Comment by LemADEC** [comment]
Try with a vanilla boat and an Archimede's ship
