### ISSUE TITLE
Wholy gun pack flamethrower has no sound...

### ISSUE THREAD

**Issue by Twilight13** [LemADEC/GunCus#16]
In the Wholy gun pack, the flamethrower is listed as using sound "asd", but there is no sound with that name, so the flamethrower is completely silent except for the sound of the "bullets" hitting the ground (little thump sounds). Not sure if this is intentional, but thought I'd mention it.

**Comment by LemADEC** [comment]
Good point, any proposal for this sound effect?

**Comment by LemADEC** [comment]
The missing sound was fixed in "WholyGunCustom 2016-02-16".
The collision sound is fixed in dev, hence closing.
