### ISSUE TITLE
SMP checksum fails with guns using no mags

### ISSUE THREAD

**Issue by Chad077** [LemADEC/GunCus#20]
Forge 10.13.4.1614
GunCustomization-1.7.10-3.47.0.-.jar
wholyguncustom-2015-11-28

[Server thread/INFO] [GunCus/]: Kicked player **LARC** because he was using modified weapons! (gunName item.WholyGunCustom.AK-47, code 1)

I've made a small pack with 2 weapons and tested it in single player. Uploaded the copy to the server and kept on being kicked due the checksum. Scratched head, download Wholy, changed a single weapon's "B:UsingMags=false", again copied the exact copy to the server which also resulted in a kick.

Cheers,

**Comment by LemADEC** [comment]
The mod validates the gun with its bullets. Code 1 means the gun is present on both ends, but its name/bullet/mags/parameters are different. There's probably a mixup in your copy between client and server, maybe in the use of lower/UPPER cases or something alike.

Please provide the full logs from both client and server.

**Comment by Chad077** [comment]
Hi LemADEC,

I just have to repeat, the copies from server has originated from the client in all instances. This morning I removed all mods leaving only the Official guns. Modded the g17 to not use mags and copied it to the server with a checksum. Checksum validated so definitely exact copies on client and server in all three instances of my tests. So reverted back the official g17 use mags to true and all worked fine.

This might be of interest, the "'[I@28ed9e00'" seems like pointer rather than a value.
**--- with mags off ---**
fml-server-latest.log:[13:06:38] [Server thread/INFO] [GunCus/]: Sending clientValidation packet 'item.Official.g17' 0 5 '[I@28ed9e00' 1.0
**--- with mags on ---**
fml-server-latest.log:[13:20:48] [Server thread/INFO] [GunCus/]: Sending clientValidation packet 'item.Official.g17' 0 5 '3' 1.0

[Logs.zip](https://github.com/LemADEC/GunCus/files/458090/Logs.zip)

**Comment by LemADEC** [comment]
Yes, that pointer won't work properly during the checksum.
Guns without mags didn't work properly in MC1.6.4, I can't quite remember if it was fixed in 1.7 or 1.9, eitherway checksum will fail with them in SMP.

**Comment by Chad077** [comment]
Awesome, thanks mate.

**Comment by Chad077** [comment]
Doh... :)

**Comment by LemADEC** [comment]
Try this version (rename .zip to .jar)
[GunCustomization-1.7.10-3.48.0.-.zip](https://github.com/LemADEC/GunCus/files/465039/GunCustomization-1.7.10-3.48.0.-.zip)

**Comment by LemADEC** [comment]
Did it fix it for you?

**Comment by Chad077** [comment]
Apologies LemADEC, somehow I missed that notification email.

Tried it with both my guns as well as the official g17 with no mags but it still fails. 

Server now sends what looks to be the correct packet.
fixed\fml-server-latest.log:[13:20:48] [Server thread/INFO] [GunCus/]: Sending clientValidation packet 'item.Official.g17' 0 5 '3' 1.0
FYI - Sever no longer seems to log packets for custom guns as above.

End result is still a kick.
fml-server-latest.log:[12:09:52] [Server thread/INFO] [GunCus/]: Kicked player **LARC** because he was using modified weapons! (gunName item.Official.g17, code 1)

**Comment by LemADEC** [comment]
[GunCustomization-1.7.10-3.49.0.-.zip](https://github.com/LemADEC/GunCus/files/601723/GunCustomization-1.7.10-3.49.0.-.zip)
Try with this version

**Comment by LemADEC** [comment]
@Chad077 was the fix effective for you?
