### ISSUE TITLE
Auto building of source

### ISSUE THREAD

**Issue by Ristellise** [LemADEC/GunCus#21]
Heya.
Have you ever though of building source code by usng a continuous integration? Just curious. i could make you if you need to.

**Comment by LemADEC** [comment]
I've already setup such on other projects but I don't like it as players using invalid/unstable versions and spam the issue the tracker.

**Comment by Ristellise** [comment]
but it helps you debug the unstable branches. well your opinion.
anyways which modpack licence should we follow? curseforge or github?
PS : the ferret business modpack is going to use your mod is the next version of the modpack

**Comment by LemADEC** [comment]
You can use the mod in any public modpack provided you credit the author and link to the Curse mod page.
