### ISSUE TITLE
Gun name changes

### ISSUE THREAD

**Issue by Breadabix** [LemADEC/GunCus#22]
Is there a way to easily change the names of the weapons. I have tried changing the name in the .cfg file, for example aek971.cfg, but it has not worked properly. I tried changing it to AK-74, but it changed it to item.Official.AK-74.name. Thanks

**Comment by LemADEC** [comment]
Filenames needs to be lower case, changing to upper case or adding dash in the filename will cause issues.
Translation is handled by the language files, in the lang folder, as usual.

**Comment by Breadabix** [comment]
What about the 'Name of the gun' option within the cfg file, thats what I changed to AK-74, along with the name of the gun in the language file. That was what produced the item.Official.AK-74.name. Do I need to change the name of the file to make it register the name change?

**Comment by LemADEC** [comment]
The 'Name of the gun' option is about the internal registry name of the gun. The displayed name is the one in the language file.
