### ISSUE TITLE
1.7.10 issues to fix

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/GunCus#3]
- [x] Sounds for custom pack
- [x] Bullet jumping through glass blocks
- [x] Grenade should explode on collision after 5 ticks
- [x] Bubble particles not visible (or not triggered ?)
- [x] Iron sights on all guns (right click with no scope)
- [x] Normal sounds for extra pack (silencer sounds work for wholys)
- [x] Scopes don't zoom in, they just bring up a crosshair
- [x] Weapon box
- [x] Mag box
- [x] Gun box
- [x] Bullet box
- [x] Ammo box
- [x] magazine names for custom pack
- [x] Textures in NEI? (magazines are causing it?) (everything after a magazine is problematic and if mags are gone its fine)
- [x] When you use a mine and trigger it, the mine drops as an item
- [x] Anti-cheat is non functional (barret delay)
- [x] Missing impact sound (and particles?)
- [x] M320 not working in SMP?
- [ ] Missing localization in SMP
- [x] Hot bar still visible while aiming

**Comment by LemADEC** [comment]
Localization has its own ticket #4, other issues are fixed => closing

**Comment by ghost** [comment]
Why does grenade explode 5 ticks after impact? Why not make it a dmg sphere
with a 4 to 5 block radius in all directions, and detonation after 10 ticks
after throwing ? It can detonate in the air and do dmg. More realistic :P

**Comment by LemADEC** [comment]
In real life, your main concern about a weapon, is blowing up too soon, on you. Hence, 'active' weapons have safety fuse that prevent 'delivery' in the few moments following launch. For a grenade, if you hit something before that fuse, it'll not trigger and bounce, then use a slower trigger. If you pass the threshold, it'll explode on first collision.

In other words, a crude grenade would explode after x ticks from launch (plus a bit of RNG). A modern one, would explode on contact pass the safety fuse.
That being said, I think the current safety fuse is a bit long.
