### ISSUE TITLE
Unable to hit anything up close

### ISSUE THREAD

**Issue by Haggle1996** [LemADEC/GunCus#8]
When creatures are closer than about 5 blocks, but far enough away you can't punch them, 100% of all shots miss. SSP, latest version. Each shot spams out something like '[GunCus]: accuracy 92 vs spray 100. Weapon doesn't matter -- they all miss.

EDIT: When mobs are up close, the gun does punch damage instead of bullet damage.

Also, very nice mod! Thank you for keeping it alive.

**Comment by LemADEC** [comment]
The logs spam is already fixed in dev.
Close range ineffectiveness is probably a regression, I'll have a look into that.

**Comment by LemADEC** [comment]
Fixed in latest update
